filter:
    excluded_paths:
        - 'tests/*'
        - 'scripts/*'
build:
    environment:
        php:
            #version: 7.0.7
            version: 5.3.5
    tests:
        override:
            -
                command: './bin/phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
